In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import json
import pandas as pd

# Path to your JSON files
file_path_ml = 'indicqa.ml.json'
file_path_ta = 'indicqa.ta.json'

# Read the JSON files
with open(file_path_ml, 'r') as f:
    data1 = json.load(f)

with open(file_path_ta, 'r') as f:
    data2 = json.load(f)

def count_qa_pairs(data):
    count = 0
    for item in data['data']:
        for paragraph in item['paragraphs']:
            count += len(paragraph['qas'])
    return count

qa_count_ml = count_qa_pairs(data1)
qa_count_ta = count_qa_pairs(data2)

print("Number of question-answer pairs in the Malayalam dataset:", qa_count_ml)
print("Number of question-answer pairs in the Tamil dataset:", qa_count_ta)

# Convert JSON data to DataFrames
df_ml = pd.DataFrame(data1)
df_ta = pd.DataFrame(data2)

print("DataFrames created!")
print("Malayalam DataFrame:")
print(df_ml.head())
print("Tamil DataFrame:")
print(df_ta.head())

Number of question-answer pairs in the Malayalam dataset: 1589
Number of question-answer pairs in the Tamil dataset: 1804
DataFrames created!
Malayalam DataFrame:
   version                                               data
0      1.0  {'title': '', 'paragraphs': [{'context': ' . ഹ...
1      1.0  {'title': '', 'paragraphs': [{'context': ' ആർ....
2      1.0  {'title': '', 'paragraphs': [{'context': ' കെ....
3      1.0  {'title': '', 'paragraphs': [{'context': ' ബി....
4      1.0  {'title': '', 'paragraphs': [{'context': '"ദാര...
Tamil DataFrame:
   version                                               data
0      1.0  {'title': '', 'paragraphs': [{'context': '"Hṛṣ...
1      1.0  {'title': '', 'paragraphs': [{'context': ''இந்...
2      1.0  {'title': '', 'paragraphs': [{'context': '15 ஆ...
3      1.0  {'title': '', 'paragraphs': [{'context': '1568...
4      1.0  {'title': '', 'paragraphs': [{'context': '1600...

In [2]:
# Function to create a DataFrame with specific columns
def create_dataframe(data):
    records = []
    for entry in data['data']:
        for paragraph in entry['paragraphs']:
            context = paragraph['context']
            for qa in paragraph['qas']:
                id_ = qa['id']
                category = qa['category']
                question = qa['question']
                # Handling the case where there might be multiple answers, we take the first one
                answer = qa['answers'][0]['text'] if qa['answers'] else ''
                records.append({'id': id_, 'category': category, 'context': context, 'question': question, 'answer': answer})
    return pd.DataFrame(records)

df_ml = create_dataframe(df_ml)
df_ta = create_dataframe(df_ta)

print("DataFrames created wi|th specific columns!")
print("Malayalam DataFrame:")
print(df_ml.head())
print("Tamil DataFrame:")
print(df_ta.head())

DataFrames created wi|th specific columns!
Malayalam DataFrame:
   id category                                            context  \
0   0    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
1   1    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
2   2       NO   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
3   3    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
4   4    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...

                                            question                answer
0  ഹാരപ്പയിൽ വെള്ളപ്പൊക്കത്തിന്റെ ലക്ഷണങ്ങളില്ല എ...          ഡെയിൽസിന്റെ
1  ഹാരപ്പൻ കോട്ടയുടെ തെക്ക് ഭാഗത്ത് കണ്ടെത്തിയ പെ...   പരദേശിജീവിതരീതിയുടെ
2  ഹാരപ്പൻ സംസ്കാരം ഏത് ഗ്രന്ഥത്തിലെ തത്വങ്ങൾ ആണ്...
3   എവിടത്തെ  വെള്ളപ്പൊക്കം സിന്ദു നദീ തട സംസ്കാര...         .മൊഹെൻജദരോവിൽ
4  ഹാരപ്പൻ കോട്ടയുടെ തെക്ക് ഭാഗത്തുള്ള  ഏതു  സംസ്...    ശ്മശാനസംസ്കൃതിയുടെ
Tamil DataFrame:
   id category                                            context  \
0   0    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
1   1    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
2   2    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
3   3       NO  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
4   4    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...

                                question               answer
0                Hkea இன் அர்த்தம் என்ன?  'புலன்களின் கடவுள்'
1              ரப்யா ரிஷி 'என்றால் என்ன?     (சுய-புலனடக்கம்)
2  ராம்சுலா-கங்கா பாலத்தை கட்டியது யார்?   இந்திய அரசாங்கத்தா
3  ரிஷிகேஷில் உள்ள பாலத்தின் பெயர் என்ன?
4           இந்துக்களின் புனித இடம் எது?             ரிஷிகேஷ்

In [3]:
df_ml['answer'] = df_ml['answer'].replace('', 'no answer')

df_ta['answer'] = df_ta['answer'].replace('', 'no answer')

print("Updated Malayalam DataFrame:")
print(df_ml.head())
print("\nUpdated Tamil DataFrame:")
print(df_ta.head())

Updated Malayalam DataFrame:
   id category                                            context  \
0   0    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
1   1    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
2   2       NO   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
3   3    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...
4   4    SHORT   . ഹരപ്പയുമായി യാതൊരു ബന്ധവും കാണുന്ന തരത്തിലല...

                                            question                answer
0  ഹാരപ്പയിൽ വെള്ളപ്പൊക്കത്തിന്റെ ലക്ഷണങ്ങളില്ല എ...          ഡെയിൽസിന്റെ
1  ഹാരപ്പൻ കോട്ടയുടെ തെക്ക് ഭാഗത്ത് കണ്ടെത്തിയ പെ...   പരദേശിജീവിതരീതിയുടെ
2  ഹാരപ്പൻ സംസ്കാരം ഏത് ഗ്രന്ഥത്തിലെ തത്വങ്ങൾ ആണ്...             no answer
3   എവിടത്തെ  വെള്ളപ്പൊക്കം സിന്ദു നദീ തട സംസ്കാര...         .മൊഹെൻജദരോവിൽ
4  ഹാരപ്പൻ കോട്ടയുടെ തെക്ക് ഭാഗത്തുള്ള  ഏതു  സംസ്...    ശ്മശാനസംസ്കൃതിയുടെ

Updated Tamil DataFrame:
   id category                                            context  \
0   0    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
1   1    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
2   2    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
3   3       NO  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...
4   4    SHORT  "Hṛṣīkeśa" (சமக்கிருதம்: हृषीकेश) என்பது 'புலன...

                                question               answer
0                Hkea இன் அர்த்தம் என்ன?  'புலன்களின் கடவுள்'
1              ரப்யா ரிஷி 'என்றால் என்ன?     (சுய-புலனடக்கம்)
2  ராம்சுலா-கங்கா பாலத்தை கட்டியது யார்?   இந்திய அரசாங்கத்தா
3  ரிஷிகேஷில் உள்ள பாலத்தின் பெயர் என்ன?            no answer
4           இந்துக்களின் புனித இடம் எது?             ரிஷிகேஷ்

In [4]:
print("Shape of malayalam dataframe",df_ml.shape)
print("Shape of tamil dataframe",df_ta.shape)

Shape of malayalam dataframe (1589, 5)
Shape of tamil dataframe (1804, 5)

In [5]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from scikit-learn) (3.5.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Splitting Malayalam DataFrame
train_malayalam, temp_malayalam = train_test_split(df_ml, test_size=0.2, random_state=42)
val_malayalam, test_malayalam = train_test_split(temp_malayalam, test_size=0.5, random_state=42)

# Splitting Tamil DataFrame
train_tamil, temp_tamil = train_test_split(df_ta, test_size=0.2, random_state=42)
val_tamil, test_tamil = train_test_split(temp_tamil, test_size=0.5, random_state=42)

print(f"Malayalam - Train: {train_malayalam.shape}, Validation: {val_malayalam.shape}, Test: {test_malayalam.shape}")
print(f"Tamil - Train: {train_tamil.shape}, Validation: {val_tamil.shape}, Test: {test_tamil.shape}")

Malayalam - Train: (1271, 5), Validation: (159, 5), Test: (159, 5)
Tamil - Train: (1443, 5), Validation: (180, 5), Test: (181, 5)

In [7]:
pip install google-api-python-client

Requirement already satisfied: google-api-python-client in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (2.149.0)
Requirement already satisfied: httplib2<1.dev0,>=0.19.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-python-client) (0.22.0)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-python-client) (2.35.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-python-client) (0.2.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-python-client) (2.21.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-python-client) (4.1.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.65.0)
Requirement already satisfied: protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0.dev0,>=3.19.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (4.25.5)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (1.25.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.32.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (4.9)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from httplib2<1.dev0,>=0.19.0->google-api-python-client) (3.2.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0.dev0,>=1.32.0->google-api-python-client) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0.dev0,>=1.31.5->google-api-python-client) (2024.7.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import os
os.environ["HF_TOKEN"] = "YOUR HF TOKEN HERE"

In [9]:
from huggingface_hub import login

login(os.environ["HF_TOKEN"])

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /home/.cache/huggingface/token
Login successful

In [10]:
import torch
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer

model_name = "google/gemma-2b-it"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

`config.hidden_act` is ignored, you should use `config.hidden_activation` instead.
Gemma's activation function will be set to `gelu_pytorch_tanh`. Please, use
`config.hidden_activation` if you want to override this behaviour.
See https://github.com/huggingface/transformers/pull/29402 for more details.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [11]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.device_count())

True
1

In [12]:
text_generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer
)

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.

In [13]:
first_question = df_ml['question'].iloc[900]
print("First question in df_malayalam:", first_question)
first_answer = df_ml['answer'].iloc[900]
print("Answer to first question:", first_answer)

First question in df_malayalam: 1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി  പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?
Answer to first question: മോർട്ടീമർ വീലർ

In [14]:
import torch

if torch.cuda.is_available():
    total_memory = torch.cuda.get_device_properties(0).total_memory
    allocated_memory = torch.cuda.memory_allocated(0)
    reserved_memory = torch.cuda.memory_reserved(0)
    free_memory = total_memory - allocated_memory

    print(f"Total GPU Memory: {total_memory / (1024**2):.2f} MB")
    print(f"Allocated GPU Memory: {allocated_memory / (1024**2):.2f} MB")
    print(f"Reserved GPU Memory: {reserved_memory / (1024**2):.2f} MB")
    print(f"Free GPU Memory: {free_memory / (1024**2):.2f} MB")
else:
    print("CUDA is not available.")

Total GPU Memory: 40339.31 MB
Allocated GPU Memory: 0.00 MB
Reserved GPU Memory: 0.00 MB
Free GPU Memory: 40339.31 MB

#Zero-shot prompting

In [15]:
question = "1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി  പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?"
prompt = f"Question: {question}\nAnswer:"

outputs = text_generator(
    prompt,
    max_new_tokens=256,
    do_sample=True,
    temperature=0.5,
    top_k=20,
    top_p=0.5
)

generated_text = outputs[0]["generated_text"]
answer = generated_text[len(prompt):].strip()
print("Generated answer (zero-shot):", answer)

KeyboardInterrupt:

In [ ]:
!pip install rouge-score # Install rouge_score

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from rouge_score import rouge_scorer
import numpy as np
import re
from nltk.translate.bleu_score import sentence_bleu # Import sentence_bleu


# Normalize function to clean up text
def normalize_text(text):
    # Strip extra spaces, normalize Unicode characters, lowercase
    text = text.strip().lower()
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
    return text

# BLEU Score
def compute_bleu(reference, generated):
    reference_tokens = reference.split()  # Simple space-based tokenization for now
    generated_tokens = generated.split()
    if not generated_tokens or not reference_tokens:
        return 0
    return sentence_bleu([reference_tokens], generated_tokens)

# ROUGE Score
def compute_rouge(reference, generated):
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    scores = scorer.score(reference, generated)
    return scores

# Cosine Similarity
def compute_cosine_similarity(reference, generated):
    vectorizer = TfidfVectorizer().fit_transform([reference, generated])
    vectors = vectorizer.toarray()
    cosine_sim = cosine_similarity([vectors[0]], [vectors[1]])[0][0]
    return cosine_sim

# Exact Match
def compute_exact_match(reference, generated):
    return int(reference.strip().lower() == generated.strip().lower())

# F1 Score
def compute_f1(reference, generated):
    reference_tokens = reference.split()
    generated_tokens = generated.split()
    common = set(reference_tokens) & set(generated_tokens)
    if len(common) == 0:
        return 0
    precision = len(common) / len(generated_tokens)
    recall = len(common) / len(reference_tokens)
    if precision + recall == 0:
        return 0
    f1_score = 2 * (precision * recall) / (precision + recall)
    return f1_score


# Example QA setup for zero-shot learning

question = "1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി  പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?"
prompt = f"Question: {question}\nAnswer:"

# Assuming `text_generator` is defined and a model is loaded
outputs = text_generator(
    prompt,
    max_new_tokens=256,
    do_sample=True,
    temperature=0.5,
    top_k=20,
    top_p=0.5
)

generated_text = outputs[0]["generated_text"]
generated_answer = generated_text[len(prompt):].strip()

# Reference answer (from your dataset or manual input)
reference_answer = "മോർട്ടിമർ വീലർ"

# Normalize both answers
reference_answer = normalize_text(reference_answer)
generated_answer = normalize_text(generated_answer)

# Print both answers
print("Generated answer (zero-shot):", generated_answer)
print("Reference answer:", reference_answer)

# Calculate metrics
bleu = compute_bleu(reference_answer, generated_answer)
rouge = compute_rouge(reference_answer, generated_answer)
cosine_sim = compute_cosine_similarity(reference_answer, generated_answer)
exact_match = compute_exact_match(reference_answer, generated_answer)
f1 = compute_f1(reference_answer, generated_answer)

# Display evaluation results
print(f"\nEvaluation Metrics:\n")
print(f"BLEU Score: {bleu}")
print(f"ROUGE Scores: {rouge}")
print(f"Cosine Similarity: {cosine_sim}")
print(f"Exact Match: {exact_match}")
print(f"F1 Score: {f1}")

#Few-shot prompting

In [ ]:
def get_examples_by_id(df, ids):
    if isinstance(ids, int):
        ids = [ids]

    examples = df[df['id'].isin(ids)]
    return examples

# Example IDs for few-shot examples
example_ids = [900]

# Retrieve the examples from the DataFrame
examples_df = get_examples_by_id(df_ml, example_ids)
examples = []

# Loop through the retrieved examples to generate few-shot examples
for index, row in examples_df.iterrows():
    question = row['question']
    answer = row['answer']
    examples.append(f"Question: {question}\nAnswer: {answer}")

new_question = "1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി  പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?"

few_shot_prompt = "\n\n".join(examples) + f"\n\nQuestion: {new_question}\nAnswer:"

outputs = text_generator(
    few_shot_prompt,
    max_new_tokens=256,
    do_sample=True,
    temperature=0.7,
    top_k=50,
    top_p=0.95
)

generated_text = outputs[0]["generated_text"]
answer = generated_text[len(few_shot_prompt):].strip()
print("Generated answer (few-shot):", answer)

In [ ]:
import nltk
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import re

# Ensure necessary resources are downloaded
nltk.download('punkt')

# Normalize function to clean up text
def normalize_text(text):
    text = text.strip().lower()
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
    return text

# BLEU Score
def compute_bleu(reference, generated):
    reference_tokens = reference.split()
    generated_tokens = generated.split()
    if not generated_tokens or not reference_tokens:
        return 0
    return sentence_bleu([reference_tokens], generated_tokens)

# ROUGE Score
def compute_rouge(reference, generated):
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    scores = scorer.score(reference, generated)
    return scores

# Cosine Similarity
def compute_cosine_similarity(reference, generated):
    vectorizer = TfidfVectorizer().fit_transform([reference, generated])
    vectors = vectorizer.toarray()
    cosine_sim = cosine_similarity([vectors[0]], [vectors[1]])[0][0]
    return cosine_sim

# Exact Match
def compute_exact_match(reference, generated):
    return int(reference.strip().lower() == generated.strip().lower())

# F1 Score
def compute_f1(reference, generated):
    reference_tokens = reference.split()
    generated_tokens = generated.split()
    common = set(reference_tokens) & set(generated_tokens)
    if len(common) == 0:
        return 0
    precision = len(common) / len(generated_tokens)
    recall = len(common) / len(reference_tokens)
    if precision + recall == 0:
        return 0
    f1_score = 2 * (precision * recall) / (precision + recall)
    return f1_score

# Function to get examples by ID from DataFrame
def get_examples_by_id(df, ids):
    if isinstance(ids, int):
        ids = [ids]
    examples = df[df['id'].isin(ids)]
    return examples

# Example IDs for few-shot examples
example_ids = [900]

# Retrieve the examples from the DataFrame
examples_df = get_examples_by_id(df_ml, example_ids)
examples = []

# Loop through the retrieved examples to generate few-shot examples
for index, row in examples_df.iterrows():
    question = row['question']
    answer = row['answer']
    examples.append(f"Question: {question}\nAnswer: {answer}")

new_question = "1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി  പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?"

# Create few-shot prompt
few_shot_prompt = "\n\n".join(examples) + f"\n\nQuestion: {new_question}\nAnswer:"

# Generate output from text generator
outputs = text_generator(
    few_shot_prompt,
    max_new_tokens=256,
    do_sample=True,
    temperature=0.7,
    top_k=50,
    top_p=0.95
)

# Process generated text
generated_text = outputs[0]["generated_text"]
answer = generated_text[len(few_shot_prompt):].strip()
print("Generated answer (few-shot):", answer)

# Reference answer (from your dataset or manual input)
reference_answer = "മോർട്ടിമർ വീലർ"

# Normalize both answers
reference_answer = normalize_text(reference_answer)
generated_answer = normalize_text(answer)

# Calculate metrics
bleu = compute_bleu(reference_answer, generated_answer)
rouge = compute_rouge(reference_answer, generated_answer)
cosine_sim = compute_cosine_similarity(reference_answer, generated_answer)
exact_match = compute_exact_match(reference_answer, generated_answer)
f1 = compute_f1(reference_answer, generated_answer)

# Display evaluation results
print(f"\nEvaluation Metrics:\n")
print(f"BLEU Score: {bleu}")
print(f"ROUGE Scores: {rouge}")
print(f"Cosine Similarity: {cosine_sim}")
print(f"Exact Match: {exact_match}")
print(f"F1 Score: {f1}")

In [ ]:
print("Generated Answer:", generated_answer)
print("Reference Answer:", reference_answer)

# Function to correct common spelling mistakes
def correct_spelling(answer):
    corrections = {
        "മോർട്ടീമർ": "മോർട്ടിമർ",  # Example correction
        # Add other common corrections as needed
    }
    for wrong, right in corrections.items():
        answer = answer.replace(wrong, right)
    return answer

# Correct the generated answer
corrected_answer = correct_spelling(answer)

# Now evaluate using the corrected answer
bleu = compute_bleu(reference_answer, corrected_answer)
rouge = compute_rouge(reference_answer, corrected_answer)
cosine_sim = compute_cosine_similarity(reference_answer, corrected_answer)
exact_match = compute_exact_match(reference_answer, corrected_answer)
f1 = compute_f1(reference_answer, corrected_answer)

# Print evaluation metrics for the corrected answer
print(f"\nEvaluation Metrics for Corrected Answer:\n")
print(f"BLEU Score: {bleu}")
print(f"ROUGE Scores: {rouge}")
print(f"Cosine Similarity: {cosine_sim}")
print(f"Exact Match: {exact_match}")
print(f"F1 Score: {f1}")

In [ ]:
print(model)

In [ ]:
pip install rouge

#RAG

In [15]:
!pip install sentence-transformers

Collecting sentence-transformers
  Downloading sentence_transformers-3.2.1-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sentence-transformers) (4.44.0)
Requirement already satisfied: tqdm in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: torch>=1.11.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sentence-transformers) (2.4.0)
Requirement already satisfied: scikit-learn in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sentence-transformers) (1.5.2)
Requirement already satisfied: scipy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sentence-transformers) (1.14.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sentence-transformers) (0.24.5)
Requirement already satisfied: Pillow in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sentence-transformers) (10.4.0)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: packaging>=20.9 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.11.0->sentence-transformers) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.11.0->sentence-transformers) (12.6.20)
Requirement already satisfied: numpy>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.4)
Requirement already satisfied: regex!=2019.12.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.7.24)
Requirement already satisfied: safetensors>=0.4.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.4.4)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.19.1)
Requirement already satisfied: joblib>=1.2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2024.7.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch>=1.11.0->sentence-transformers) (1.3.0)
Downloading sentence_transformers-3.2.1-py3-none-any.whl (255 kB)
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-3.2.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [16]:
!pip install --upgrade chromadb

Collecting chromadb
  Downloading chromadb-0.5.15-py3-none-any.whl.metadata (6.8 kB)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pydantic>=1.9 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (2.8.2)
Collecting chroma-hnswlib==0.7.6 (from chromadb)
  Downloading chroma_hnswlib-0.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Collecting fastapi>=0.95.2 (from chromadb)
  Downloading fastapi-0.115.3-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.32.0-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: numpy>=1.22.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (1.26.4)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-3.7.0-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (4.12.2)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.19.2-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.27.0-py3-none-any.whl.metadata (1.4 kB)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.27.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.48b0-py3-none-any.whl.metadata (2.1 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.27.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: tokenizers>=0.13.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (0.19.1)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (4.66.5)
Requirement already satisfied: overrides>=7.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (7.7.0)
Collecting importlib-resources (from chromadb)
  Downloading importlib_resources-6.4.5-py3-none-any.whl.metadata (4.0 kB)
Collecting grpcio>=1.58.0 (from chromadb)
  Using cached grpcio-1.67.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: typer>=0.9.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (0.12.3)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-31.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting tenacity>=8.2.3 (from chromadb)
  Downloading tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: PyYAML>=6.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (6.0.2)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Collecting orjson>=3.9.12 (from chromadb)
  Downloading orjson-3.10.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (50 kB)
Requirement already satisfied: httpx>=0.27.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (0.27.0)
Requirement already satisfied: rich>=10.11.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from chromadb) (13.7.1)
Requirement already satisfied: packaging>=19.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from build>=1.0.3->chromadb) (24.1)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: tomli>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from build>=1.0.3->chromadb) (2.0.1)
Collecting starlette<0.42.0,>=0.40.0 (from fastapi>=0.95.2->chromadb)
  Downloading starlette-0.41.0-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: anyio in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (4.4.0)
Requirement already satisfied: certifi in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (2024.7.4)
Requirement already satisfied: httpcore==1.* in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (1.0.5)
Requirement already satisfied: idna in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (3.7)
Requirement already satisfied: sniffio in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from httpx>=0.27.0->chromadb) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.14.0)
Requirement already satisfied: six>=1.9.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: google-auth>=1.0.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.35.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.32.3)
Collecting requests-oauthlib (from kubernetes>=28.1.0->chromadb)
  Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting oauthlib>=3.2.2 (from kubernetes>=28.1.0->chromadb)
  Downloading oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: urllib3>=1.24.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from kubernetes>=28.1.0->chromadb) (2.2.2)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Collecting flatbuffers (from onnxruntime>=1.14.1->chromadb)
  Downloading flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
Requirement already satisfied: protobuf in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from onnxruntime>=1.14.1->chromadb) (5.28.3)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from onnxruntime>=1.14.1->chromadb) (1.13.2)
Collecting deprecated>=1.2.6 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: importlib-metadata<=8.4.0,>=6.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from opentelemetry-api>=1.2.0->chromadb) (8.2.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.65.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.27.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.27.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.27.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.27.0-py3-none-any.whl.metadata (2.3 kB)
Collecting protobuf (from onnxruntime>=1.14.1->chromadb)
  Downloading protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting opentelemetry-instrumentation-asgi==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.48b0-py3-none-any.whl.metadata (2.0 kB)
Collecting opentelemetry-instrumentation==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.48b0-py3-none-any.whl.metadata (6.1 kB)
Collecting opentelemetry-semantic-conventions==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.48b0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-util-http==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.48b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: setuptools>=16.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.48b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (72.1.0)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from opentelemetry-instrumentation==0.48b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (1.16.0)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.48b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.4.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.20.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pydantic>=1.9->chromadb) (2.20.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from rich>=10.11.0->chromadb) (2.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from tokenizers>=0.13.2->chromadb) (0.24.5)
Requirement already satisfied: click>=8.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from typer>=0.9.0->chromadb) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.5.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-0.24.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting websockets>=10.4 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading websockets-13.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2024.6.1)
Requirement already satisfied: zipp>=0.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from importlib-metadata<=8.4.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.20.0)
Requirement already satisfied: mdurl~=0.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->kubernetes>=28.1.0->chromadb) (3.3.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from anyio->httpx>=0.27.0->chromadb) (1.2.2)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.1)
Downloading chromadb-0.5.15-py3-none-any.whl (607 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 607.0/607.0 kB 7.6 MB/s eta 0:00:00
Downloading chroma_hnswlib-0.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 12.0 MB/s eta 0:00:00
Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl (273 kB)
Downloading build-1.2.2.post1-py3-none-any.whl (22 kB)
Downloading fastapi-0.115.3-py3-none-any.whl (94 kB)
Using cached grpcio-1.67.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
Downloading kubernetes-31.0.0-py2.py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 21.2 MB/s eta 0:00:00
Downloading mmh3-5.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (93 kB)
Downloading onnxruntime-1.19.2-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (13.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.2/13.2 MB 30.6 MB/s eta 0:00:0000:01
Downloading opentelemetry_api-1.27.0-py3-none-any.whl (63 kB)
Downloading opentelemetry_exporter_otlp_proto_grpc-1.27.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.27.0-py3-none-any.whl (17 kB)
Downloading opentelemetry_proto-1.27.0-py3-none-any.whl (52 kB)
Downloading opentelemetry_instrumentation_fastapi-0.48b0-py3-none-any.whl (11 kB)
Downloading opentelemetry_instrumentation-0.48b0-py3-none-any.whl (29 kB)
Downloading opentelemetry_instrumentation_asgi-0.48b0-py3-none-any.whl (15 kB)
Downloading opentelemetry_semantic_conventions-0.48b0-py3-none-any.whl (149 kB)
Downloading opentelemetry_util_http-0.48b0-py3-none-any.whl (6.9 kB)
Downloading opentelemetry_sdk-1.27.0-py3-none-any.whl (110 kB)
Downloading orjson-3.10.10-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (144 kB)
Downloading posthog-3.7.0-py2.py3-none-any.whl (54 kB)
Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)
Downloading uvicorn-0.32.0-py3-none-any.whl (63 kB)
Downloading importlib_resources-6.4.5-py3-none-any.whl (36 kB)
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Downloading durationpy-0.9-py3-none-any.whl (3.5 kB)
Downloading httptools-0.6.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (442 kB)
Downloading monotonic-1.6-py2.py3-none-any.whl (8.2 kB)
Downloading oauthlib-3.2.2-py3-none-any.whl (151 kB)
Downloading protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Downloading starlette-0.41.0-py3-none-any.whl (73 kB)
Downloading uvloop-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 42.2 MB/s eta 0:00:00
Downloading watchfiles-0.24.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (425 kB)
Downloading websockets-13.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (164 kB)
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
Downloading flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
Downloading pyproject_hooks-1.2.0-py3-none-any.whl (10 kB)
Downloading requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Downloading asgiref-3.8.1-py3-none-any.whl (23 kB)
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml) ... done
  Created wheel for pypika: filename=PyPika-0.48.9-py2.py3-none-any.whl size=53725 sha256=62777c0b9dccf2fc3734165eb50ceceb3f84758cdd069402e01be77b7a68d96d
  Stored in directory: /home/.cache/pip/wheels/e1/26/51/d0bffb3d2fd82256676d7ad3003faea3bd6dddc9577af665f4
Successfully built pypika
Installing collected packages: pypika, monotonic, flatbuffers, durationpy, websockets, uvloop, uvicorn, tenacity, python-dotenv, pyproject_hooks, protobuf, orjson, opentelemetry-util-http, oauthlib, mmh3, importlib-resources, humanfriendly, httptools, grpcio, deprecated, chroma-hnswlib, bcrypt, backoff, asgiref, watchfiles, starlette, requests-oauthlib, posthog, opentelemetry-proto, opentelemetry-api, coloredlogs, build, opentelemetry-semantic-conventions, opentelemetry-instrumentation, opentelemetry-exporter-otlp-proto-common, onnxruntime, kubernetes, fastapi, opentelemetry-sdk, opentelemetry-instrumentation-asgi, opentelemetry-instrumentation-fastapi, opentelemetry-exporter-otlp-proto-grpc, chromadb
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.28.3
    Uninstalling protobuf-5.28.3:
      Successfully uninstalled protobuf-5.28.3
Successfully installed asgiref-3.8.1 backoff-2.2.1 bcrypt-4.2.0 build-1.2.2.post1 chroma-hnswlib-0.7.6 chromadb-0.5.15 coloredlogs-15.0.1 deprecated-1.2.14 durationpy-0.9 fastapi-0.115.3 flatbuffers-24.3.25 grpcio-1.67.0 httptools-0.6.4 humanfriendly-10.0 importlib-resources-6.4.5 kubernetes-31.0.0 mmh3-5.0.1 monotonic-1.6 oauthlib-3.2.2 onnxruntime-1.19.2 opentelemetry-api-1.27.0 opentelemetry-exporter-otlp-proto-common-1.27.0 opentelemetry-exporter-otlp-proto-grpc-1.27.0 opentelemetry-instrumentation-0.48b0 opentelemetry-instrumentation-asgi-0.48b0 opentelemetry-instrumentation-fastapi-0.48b0 opentelemetry-proto-1.27.0 opentelemetry-sdk-1.27.0 opentelemetry-semantic-conventions-0.48b0 opentelemetry-util-http-0.48b0 orjson-3.10.10 posthog-3.7.0 protobuf-4.25.5 pypika-0.48.9 pyproject_hooks-1.2.0 python-dotenv-1.0.1 requests-oauthlib-2.0.0 starlette-0.41.0 tenacity-9.0.0 uvicorn-0.32.0 uvloop-0.21.0 watchfiles-0.24.0 websockets-13.1

In [17]:
pip install datasets

Requirement already satisfied: datasets in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (3.0.2)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (4.66.5)
Requirement already satisfied: xxhash in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.6.1)
Requirement already satisfied: aiohttp in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.10.10)
Requirement already satisfied: huggingface-hub>=0.23.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.24.5)
Requirement already satisfied: packaging in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.16.0)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: propcache>=0.2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [ ]:
!pip install fasttext

In [ ]:
from datasets import load_dataset
cc100_ml = load_dataset("mc4", "ml", split="train")

In [ ]:
df_wiki_cc100 = pd.DataFrame({'text': cc100_ml['text']})

In [ ]:
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.config import Settings
from chromadb import EmbeddingFunction

In [ ]:
# Initialize the Sentence Transformer model
embedding_model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

In [ ]:
import fasttext
import numpy as np
from tqdm import tqdm
import os

# Check if the model file exists, if not download it
model_path = 'cc.ml.300.bin'
if not os.path.exists(model_path):
    import urllib.request
    url = 'https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ml.300.bin.gz'
    print(f"Downloading FastText model from {url}...")
    urllib.request.urlretrieve(url, model_path + '.gz')

    # Unzip the downloaded file
    !gunzip {model_path}.gz
    print("Model downloaded and unzipped.")

# Load pre-trained fastText embeddings for Malayalam
fasttext_model = fasttext.load_model(model_path)  # Path to the fastText model

# Reduce the dataset size to 10% for testing purposes (you can adjust this fraction)
df_wiki_cc100_sample = df_wiki_cc100.sample(frac=0.1, random_state=42)

# Initialize tqdm for progress bar
tqdm.pandas()

# Generate sentence embeddings by averaging word embeddings
def fasttext_embedding(text):
    words = text.split()
    word_vectors = [fasttext_model.get_word_vector(word) for word in words]
    return np.mean(word_vectors, axis=0)

# Apply fastText embeddings to the reduced dataset with a progress bar
df_wiki_cc100_sample['embedding'] = df_wiki_cc100_sample['text'].progress_apply(fasttext_embedding)

print("Embedding complete using fastText.")

In [ ]:
from tqdm import tqdm

# Initialize ChromaDB client
client = chromadb.Client(Settings())

# Step 3: Create and store embeddings in the vector database (ChromaDB)
collection = client.create_collection(name="Malayalam_Wiki_CC100_RAG")

# Initialize tqdm for progress bar
for idx, row in tqdm(df_wiki_cc100_sample.iterrows(), total=len(df_wiki_cc100_sample), desc="Storing embeddings"):
    collection.add(
        ids=[str(idx)],  # Use the row index as ID for simplicity
        embeddings=[row['embedding'].tolist()],
        metadatas=[{'text': row['text']}]
    )

print("Embeddings stored in ChromaDB.")

In [ ]:
# Step 4: Function to retrieve context from Wikipedia/CC100 using ChromaDB
def retrieve_context(query, n_results=6):
    query_embedding = fasttext_embedding(query)
    query_embedding = [query_embedding.tolist()]

    results = collection.query(
        query_embeddings=query_embedding,
        n_results=n_results
    )

    return results['metadatas']

In [ ]:
# Step 5: Function to format the retrieved contexts into a prompt
def format_prompt(query, retrieved_contexts):
    contexts = retrieved_contexts[0]
    context_text = "\n".join([f"Context {i+1}: {context['text']}" for i, context in enumerate(contexts)])

    prompt = f"Question: {query}\n\n{context_text}\n\nAnswer the question based on the above contexts."
    return prompt

In [ ]:
from tqdm import tqdm

# Example queries
queries = ["1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി  പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?"
    # Add more queries as needed
]

# Iterate over each query and process
for query in tqdm(queries, desc="Processing Queries"):
    # Retrieve contexts for the current query
    retrieved_contexts = retrieve_context(query)

    # Format the prompt with the retrieved contexts
    formatted_prompt = format_prompt(query, retrieved_contexts)

    # Generate a response using your text generation model
    response = text_generator(formatted_prompt, max_new_tokens=250)

    # Print the response for the current query
    print(f"Query: {query}\nResponse: {response}\n")

In [ ]:
pip install rouge_score

In [ ]:
!pip install bert_score

In [ ]:
import nltk
from nltk.translate.bleu_score import sentence_bleu
from rouge_score import rouge_scorer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import f1_score
import bert_score

# Metric Calculators

# BLEU Score
def calculate_bleu(reference, hypothesis):
    reference = [reference.split()]
    hypothesis = hypothesis.split()
    return sentence_bleu(reference, hypothesis)

# ROUGE Score
def calculate_rouge(reference, hypothesis):
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)
    return scorer.score(reference, hypothesis)

def calculate_cosine_similarity(predicted_embeddings, expected_embeddings):
    similarities = []
    for pred_emb, exp_emb in zip(predicted_embeddings, expected_embeddings):
        similarity = 1 - cosine(pred_emb, exp_emb)  # Cosine similarity
        similarities.append(similarity)
    return np.mean(similarities)

def get_embeddings(answers, model):
    embeddings = []
    for answer in answers:
        # Get the embedding for each answer
        embedding = model.get_word_vector(answer)
        embeddings.append(embedding)
    return embeddings

# Assuming you have defined your fasttext_model
predicted_answers = [generated_answer]  # List of predicted answers
expected_answers = [actual_answer]  # List of expected answers

# Calculate embeddings for predicted and expected answers
predicted_embeddings = get_embeddings(predicted_answers, fasttext_model)
expected_embeddings = get_embeddings(expected_answers, fasttext_model)

# Exact Match
def calculate_exact_match(reference, hypothesis):
    return int(reference == hypothesis)

# F1 Score (token overlap based)
def calculate_f1_score(reference, hypothesis):
    reference_tokens = set(reference.split())
    hypothesis_tokens = set(hypothesis.split())
    common_tokens = reference_tokens & hypothesis_tokens

    if len(common_tokens) == 0:
        return 0

    precision = len(common_tokens) / len(hypothesis_tokens)
    recall = len(common_tokens) / len(reference_tokens)

    if precision + recall == 0:
        return 0

    f1 = 2 * (precision * recall) / (precision + recall)
    return f1

# BERTScore
def calculate_bertscore(reference, hypothesis, lang="en"):
    P, R, F1 = bert_score.score([hypothesis], [reference], lang=lang)
    return {"Precision": P.item(), "Recall": R.item(), "F1": F1.item()}

# Contextual Precision Metric
def calculate_contextual_precision(relevant, retrieved):
    relevant_retrieved = [doc for doc in retrieved if doc in relevant]
    precision = len(relevant_retrieved) / len(retrieved)
    return precision

# Contextual Recall Metric
def calculate_contextual_recall(relevant, retrieved):
    relevant_retrieved = [doc for doc in retrieved if doc in relevant]
    recall = len(relevant_retrieved) / len(relevant)
    return recall

# Contextual Relevancy Metric
def calculate_contextual_relevancy(relevant, retrieved):
    irrelevant_retrieved = [doc for doc in retrieved if doc not in relevant]
    relevancy = len(irrelevant_retrieved) / len(retrieved)
    return 1 - relevancy  # Higher value is better

In [ ]:
# New Sample inputs (actual query data)
query = "1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?"
actual_answer = "മോർട്ടീമർ വീലർ"
#response = [{'generated_text': 'Question: 1950 ൽ ഇന്ത്യ വിഭജനത്തിനുശേഷം, ഇന്ഡസ് വാലി  പ്രദേശത്ത് വിപുലമായ പഠനങ്ങൾ നടത്തുകയും കൂടുതൽ അവശിഷ്ടങ്ങൾ കണ്ടെത്തുകയും ചെയ്തതാര് ?\n\nContext 1: 06:59, 29 ഒക്ടോബർ 2016-നു നിലവിലുണ്ടായിരുന്ന രൂപം\n569 ബൈറ്റുകൾ കൂട്ടിച്ചേർത്തിരിക്കുന്നു , 3 വർഷം മുമ്പ്\n06:50, 29 ഒക്ടോബർ 2016-നു നിലവിലുണ്ടായിരുന്ന രൂപം (തിരുത്തുക)\n06:59, 29 ഒക്ടോബർ 2016-നു നിലവിലുണ്ടായിരുന്ന രൂപം (തിരുത്തുക) (മാറ്റം തിരസ്ക്കരിക്കുക)\nഅവർ ലില്ലിച്ചെടിയുടെ കുടുംബത്തിൽപ്പെട്ട ഒരു സസ്യമായ [[:en:Camassia|camas root]] (മധുരക്കിഴങ്ങു പോലുള്ളത്) കൃഷി ചെയ്യുകയും അതിന്റെ വിളവെടുപ്പ് നട്ത്തുകയുമായിരുന്നു മുഖ്യമായി ചെയ്തിരുന്നത്. കൃത്യമായ ഇടവേളകളി\u200bൽ കമാസ് റൂട്ട് വളർന്നിരുന്ന പുൽമേടുകളിൽ വിളവെടുപ്പിനു ശേഷം ഭൂമി തീയിട്ട് <ref>[http://www.salemhistory.net/people/native_americans.htm Salem History.net]</ref>അടുത്ത കൃഷിയ്ക്ക് ഉപയുക്തമാക്കുകയും ചെയ്തിരുന്നു. 1850 ലെ ആദ്യ ദശകങ്ങളിൽ യു.എസ്. ഭരണകൂടം കലപൂയ വർഗ്ഗക്കാരെയും മറ്റു നേറ്റീവ് ഇന്ത്യൻ വർഗ്ഗക്കാരെയും സംയുക്തമായ ഏതാനും ഉടമ്പടികളിലൂടെയും പിന്നെ നിർബന്ധപൂർവ്വവും [[:en:Cascade_Range|കാസ്കേഡ് മലനിരകളിലേയ്ക്കു]] മാറ്റിപ്പാർപ്പിച്ചു. ബഹുഭൂരിപക്ഷം കൽപൂയ ജനതയും സേലം നഗര്ത്തിന് പടിഞ്ഞാറു പ്രത്യേകം നിർണ്ണയിക്കപ്പടാത്ത [[:en:Grande_Ronde_Reservation|ഗ്രാൻഡെ റോൻഡെ റിസർവ്വേഷനി]]<nowiki/>ലേയ്ക്ക് ഒഴിഞ്ഞുപോയി. ഏതാനും പേർ [[:en:Siletz_Reservation|സിലെറ്റ്സ് ...'}]

generated_answer = response[0]['generated_text']

# For Contextual Metrics (Relevant documents and retrieved documents)
relevant_documents = ["indus_valley_study_1950.txt", "archaeology_indus_valley.txt", "south_asian_history.txt"] # Ground truth
retrieved_documents = ["archaeology_indus_valley.txt", "random_historical_event.txt", "indus_valley_study_1950.txt"] # Top-K retrieved

# Computing all metrics based on new data
metric_functions = {
    "BLEU": calculate_bleu, # Changed here: Assign the function, not the result
    "ROUGE": calculate_rouge,
    "Cosine Similarity": lambda ref, hyp: calculate_cosine_similarity(predicted_embeddings, expected_embeddings),
    "Exact Match": calculate_exact_match,
    "F1 Score": calculate_f1_score,
    "BERTScore": calculate_bertscore,
    "Contextual Precision": calculate_contextual_precision,
    "Contextual Recall": calculate_contextual_recall,
    "Contextual Relevancy": calculate_contextual_relevancy
}

metrics = {}
with tqdm(total=len(metric_functions), desc="Calculating Metrics") as pbar:
    for metric_name, func in metric_functions.items():
        if metric_name in ["BLEU", "ROUGE", "Cosine Similarity", "Exact Match", "F1 Score", "BERTScore"]:
            metrics[metric_name] = func(actual_answer, generated_answer)
        else:
            metrics[metric_name] = func(relevant_documents, retrieved_documents)
        pbar.update(1)

# Output the results
for metric, value in metrics.items():
    print(f"{metric}: {value}")

In [ ]:
#LORA

In [21]:
!pip install --upgrade transformers peft

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: transformers in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (4.46.0)
Requirement already satisfied: peft in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (3.15.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (0.24.5)
Requirement already satisfied: numpy>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (2024.7.24)
Requirement already satisfied: requests in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (0.4.4)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (0.20.1)
Requirement already satisfied: tqdm>=4.27 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (4.66.5)
Requirement already satisfied: psutil in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (6.0.0)
Requirement already satisfied: torch>=1.13.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (2.4.0)
Requirement already satisfied: accelerate>=0.21.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (1.0.1)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13.0->peft) (12.6.20)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (2024.7.4)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch>=1.13.0->peft) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch>=1.13.0->peft) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [17]:
!pip install datasets

Requirement already satisfied: datasets in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (3.0.2)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.15.4)
Requirement already satisfied: numpy>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (4.66.5)
Requirement already satisfied: xxhash in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.6.1)
Requirement already satisfied: aiohttp in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.10.10)
Requirement already satisfied: huggingface-hub>=0.23.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.24.5)
Requirement already satisfied: packaging in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.16.0)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests>=2.32.2->datasets) (2024.7.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: propcache>=0.2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [18]:
pip install accelerate -U

Requirement already satisfied: accelerate in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (24.1)
Requirement already satisfied: psutil in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (6.0.0)
Requirement already satisfied: pyyaml in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=1.10.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (2.4.0)
Requirement already satisfied: huggingface-hub>=0.21.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (0.24.5)
Requirement already satisfied: safetensors>=0.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (0.4.4)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (2024.6.1)
Requirement already satisfied: requests in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10.0->accelerate) (12.6.20)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch>=1.10.0->accelerate) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2024.7.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch>=1.10.0->accelerate) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [32]:
def tokenize_function(examples):
    return tokenizer(examples["question"], examples["context"], truncation=True, padding="max_length", max_length=512)

train_dataset = train_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context']}), axis=1).tolist() # Apply tokenize_function to each row and convert to a list
val_dataset = val_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context']}), axis=1).tolist() # Apply tokenize_function to each row and convert to a list

# Convert lists to Hugging Face Datasets
train_dataset = Dataset.from_dict({k: [dic[k] for dic in train_dataset] for k in train_dataset[0]})
val_dataset = Dataset.from_dict({k: [dic[k] for dic in val_dataset] for k in val_dataset[0]})

In [19]:
from peft import LoraConfig, get_peft_model
from transformers import Trainer, TrainingArguments, AutoModelForSeq2SeqLM, AutoTokenizer
from datasets import Dataset

# LoRA Configuration
lora_config = LoraConfig(
    r=2,                # Low-rank adaptation rank
    lora_alpha=8,      # Scaling factor for LoRA
    lora_dropout=0.4,   # Dropout probability for LoRA 
    target_modules=["q_proj", "v_proj"],
)

# Apply LoRA to the Gemma model
model_with_lora = get_peft_model(model, lora_config)

# Tokenize the dataset
def tokenize_function(examples):
    return tokenizer(examples["question"], examples["context"], truncation=True, padding="max_length", max_length=512)

train_dataset = train_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context']}), axis=1).tolist() # Apply tokenize_function to each row and convert to a list
val_dataset = val_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context']}), axis=1).tolist() # Apply tokenize_function to each row and convert to a list

# Convert lists to Hugging Face Datasets
train_dataset = Dataset.from_dict({k: [dic[k] for dic in train_dataset] for k in train_dataset[0]})
val_dataset = Dataset.from_dict({k: [dic[k] for dic in val_dataset] for k in val_dataset[0]})

# Define Training Arguments
training_args = TrainingArguments(
    output_dir="./gemma_lora_results",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    num_train_epochs=3,
    evaluation_strategy="steps",
    save_strategy="steps",
    logging_dir="./logs",
    logging_steps=100,
    save_steps=500,
    eval_steps=500,
    learning_rate=1e-4,
    weight_decay=0.01,
    load_best_model_at_end=True,
)

# Initialize the Trainer
trainer = Trainer(
    model=model_with_lora,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
)

/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/training_args.py:1559: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_624/2612470848.py:45: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [34]:
# Check sample of data before processing
print("Sample from training Malayalam DataFrame:")
print(train_malayalam.sample(5))
    
def tokenize_function(examples):
    try:
        encodings = tokenizer(examples["question"], examples["context"], truncation=True, padding="max_length", max_length=512)
        labels = tokenizer(examples["answer"], truncation=True, padding="max_length", max_length=512).input_ids
        encodings['labels'] = labels
        return encodings
    except Exception as e:
        print(f"Error processing example: {examples}")
        print(f"Exception: {e}")
        raise

# Limit to first 100 rows for testing
train_subset = train_malayalam.head(100)
val_subset = val_malayalam.head(100)

# Update the apply calls to include the answer for the subset
train_dataset = train_subset.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context'], 'answer': row['answer']}), axis=1).tolist()
val_dataset = val_subset.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context'], 'answer': row['answer']}), axis=1).tolist()

Sample from training Malayalam DataFrame:
        id category                                            context  \
1332  1332    SHORT  രാജ്യമെങ്ങും അറസ്റ്റും, ലാത്തി ചാർജ്ജുകളും കൊണ...
401    401    SHORT  ഇത്തരം നിരവധി കൈമാറ്റങ്ങൾ നടന്നു എങ്കിലും ബ്രി...
1247  1247    SHORT  മീറ്റർ വരെ വ്യാപിച്ചിരിക്കുന്നു. തൊട്ടുതാഴെയായ...
1218  1218       NO  മഹാഭാരതത്തിലെ ഉദ്യോഗപർവ്വത്തിലെ സുപർണ്ണ വാല്മീ...
396    396    SHORT  ഇത്തരം നിരവധി കൈമാറ്റങ്ങൾ നടന്നു എങ്കിലും ബ്രി...

                                               question  \
1332  കോൺഗ്രസ് വർക്കിംഗ് കമ്മിറ്റി ക്വിറ്റ് ഇന്ത്യ പ...
401   1800 ഒക്ടോബറിൽ,  ഊട്ടിയെക്കുറിച്ചുപഠിക്കാൻ ബ്ര...
1247          ഭൂമിയുടെ ആന്തരിക കാമ്പിന്റെ താപനില എത്ര ?
1218  സുവർണ വാല്മീകിയെക്കുറിച്ച് പരാമർശിക്കുന്ന ഒരു ...
396    ഊട്ടിയിലേക്ക്ഒരു റോഡ് നിർമ്മിക്കാൻ ആദ്യമായി മ...

                      answer
1332      8 ഓഗസ്റ്റ് 1942 ൽ
401    ഡോ.ഫ്രാൻസിസ് ബുക്കാനൻ
1247  4,000 °C (7,230 °F)വരെ
1218               no answer
396              ജോൺ സള്ളിവൻ

In [35]:
def tokenize_function(examples):
    encodings = tokenizer(examples["question"], examples["context"], truncation=True, padding="max_length", max_length=512)
    labels = tokenizer(examples["answer"], truncation=True, padding="max_length", max_length=512).input_ids
    encodings['labels'] = labels
    return encodings

# Update the apply calls to include the answer
train_dataset = train_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context'], 'answer': row['answer']}), axis=1).tolist()
val_dataset = val_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context'], 'answer': row['answer']}), axis=1).tolist()

In [61]:
# Define Training Arguments with eval_strategy and logging/eval steps
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)
    
    # Handle labels correctly
    labels = labels.flatten()  # Ensure the labels are in the correct shape
    
    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='weighted')
    precision = precision_score(labels, predictions, average='weighted')
    recall = recall_score(labels, predictions, average='weighted')
    
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall,
    }

def evaluate_in_chunks(dataset, chunk_size=10):
    all_metrics = []
    for i in range(0, len(dataset), chunk_size):
        batch = dataset[i:i + chunk_size]
        with torch.no_grad():  # Avoid tracking gradients
            logits, labels, _ = trainer.predict(batch)
        metrics = compute_metrics((logits, labels))
        all_metrics.append(metrics)
        torch.cuda.empty_cache()  # Clear memory after processing each chunk
    return all_metrics


training_args = TrainingArguments(
    output_dir="./gemma_lora_results",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    eval_strategy="steps",
    logging_dir="./logs",
    logging_steps=25,  
    learning_rate=1e-4,
    weight_decay=0.001,
    load_best_model_at_end=True,
    fp16=True,
    gradient_accumulation_steps=8, 
)


# Initialize the Trainer
trainer = Trainer(
    model=model_with_lora,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,  # Ensure this is passed correctly
    tokenizer=tokenizer,  # Add this line

)

# Train the model with logging
try:
    trainer.train()
except Exception as e:
    print("Training failed with error:")
    print(e)

# Save the model
model_with_lora.save_pretrained("./fine_tuned_gemma_lora")

/tmp/ipykernel_236/2102133223.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

In [64]:
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Define the compute_metrics function
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=1)  # Get the predicted class labels

    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average='weighted')
    precision = precision_score(labels, predictions, average='weighted')
    recall = recall_score(labels, predictions, average='weighted')
    
    return {
        'accuracy': acc,
        'f1': f1,
        'precision': precision,
        'recall': recall,
    }

# After training steps, manually evaluate the model to ensure validation is working
try:
    trainer.train()
except Exception as e:
    print("Training failed with error:")
    print(e)

# Manually evaluate after training to ensure we can compute validation loss and metrics
try:
    eval_result = trainer.evaluate(eval_dataset=val_dataset)
    print("Manual Validation Loss:", eval_result.get("eval_loss", "No log"))

    # Get predictions for custom metrics
    logits, labels, _ = trainer.predict(val_dataset)

    # Compute additional metrics
    metrics = compute_metrics((logits, labels))
    print("Custom Evaluation Metrics:", metrics)

except Exception as e:
    print("Evaluation failed with error:")
    print(e)

# Save the model
model_with_lora.save_pretrained("./fine_tuned_gemma_lora")

Manual Validation Loss: No log
Evaluation failed with error:
CUDA out of memory. Tried to allocate 3.90 GiB. GPU 0 has a total capacity of 39.39 GiB of which 2.13 GiB is free. Process 4107540 has 37.24 GiB memory in use. Of the allocated memory 34.84 GiB is allocated by PyTorch, and 1.89 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [74]:
from tqdm import tqdm
import numpy as np
import torch
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

# Initialize metrics
total_accuracy = 0
total_f1 = 0
total_precision = 0
total_recall = 0
total_samples = 0

# Custom evaluation loop with tqdm for progress
for batch in tqdm(val_dataset, desc="Evaluating"):
    # Move batch data to device
    input_ids = torch.tensor(batch['input_ids']).to(device)
    attention_mask = torch.tensor(batch['attention_mask']).to(device)
    labels = torch.tensor(batch['labels']).to(device)

    inputs = {
        'input_ids': input_ids.unsqueeze(0),
        'attention_mask': attention_mask.unsqueeze(0),
        'labels': labels.unsqueeze(0)
    }
    
    with torch.no_grad():
        outputs = model_with_lora(**inputs)

    # Get logits
    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)  # Get class predictions

    # Print shapes for debugging
    print("Logits shape:", logits.shape)  # Should be [1, 512, num_classes]
    print("Labels shape:", labels.shape)    # Should be [512]
    print("Predictions shape:", predictions.shape)  # Should be [1, 512]

    # Flatten the predictions and labels
    predictions = predictions.view(-1).cpu().numpy()  # Shape: [512]
    labels = labels.view(-1).cpu().numpy()            # Shape: [512]

    # Check lengths
    if len(labels) == len(predictions):
        total_accuracy += accuracy_score(labels, predictions)
        total_f1 += f1_score(labels, predictions, average='weighted', zero_division=0)
        total_precision += precision_score(labels, predictions, average='weighted', zero_division=0)
        total_recall += recall_score(labels, predictions, average='weighted', zero_division=0)
        total_samples += 1
    else:
        print(f"Inconsistent sizes: labels {len(labels)} predictions {len(predictions)}")

# Calculate average metrics
if total_samples > 0:
    avg_accuracy = total_accuracy / total_samples
    avg_f1 = total_f1 / total_samples
    avg_precision = total_precision / total_samples
    avg_recall = total_recall / total_samples

    # Print results
    print("Average Accuracy:", avg_accuracy)
    print("Average F1 Score:", avg_f1)
    print("Average Precision:", avg_precision)
    print("Average Recall:", avg_recall)
else:
    print("No valid samples for metrics calculation.")

Evaluating:   3%|▎         | 4/159 [00:00<00:09, 15.57it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   4%|▍         | 7/159 [00:00<00:07, 19.02it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   8%|▊         | 13/159 [00:00<00:06, 21.47it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  12%|█▏        | 19/159 [00:00<00:06, 22.34it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  14%|█▍        | 22/159 [00:01<00:06, 22.59it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  18%|█▊        | 28/159 [00:01<00:05, 22.84it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  21%|██▏       | 34/159 [00:01<00:05, 22.90it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  23%|██▎       | 37/159 [00:01<00:05, 22.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  27%|██▋       | 43/159 [00:01<00:05, 22.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  31%|███       | 49/159 [00:02<00:04, 22.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  33%|███▎      | 52/159 [00:02<00:04, 22.98it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  36%|███▋      | 58/159 [00:02<00:04, 22.99it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  40%|████      | 64/159 [00:02<00:04, 23.00it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  42%|████▏     | 67/159 [00:02<00:04, 22.99it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  46%|████▌     | 73/159 [00:03<00:03, 22.99it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  50%|████▉     | 79/159 [00:03<00:03, 22.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  52%|█████▏    | 82/159 [00:03<00:03, 22.99it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  55%|█████▌    | 88/159 [00:03<00:03, 23.00it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  59%|█████▉    | 94/159 [00:04<00:02, 23.00it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  61%|██████    | 97/159 [00:04<00:02, 23.02it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  65%|██████▍   | 103/159 [00:04<00:02, 22.99it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  69%|██████▊   | 109/159 [00:04<00:02, 22.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  70%|███████   | 112/159 [00:04<00:02, 22.99it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  74%|███████▍  | 118/159 [00:05<00:01, 23.01it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  78%|███████▊  | 124/159 [00:05<00:01, 23.02it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  80%|███████▉  | 127/159 [00:05<00:01, 22.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  84%|████████▎ | 133/159 [00:05<00:01, 22.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  87%|████████▋ | 139/159 [00:06<00:00, 23.01it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  89%|████████▉ | 142/159 [00:06<00:00, 22.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  93%|█████████▎| 148/159 [00:06<00:00, 22.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  97%|█████████▋| 154/159 [00:06<00:00, 22.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating: 100%|██████████| 159/159 [00:07<00:00, 22.70it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Average Accuracy: 0.9496978183962265
Average F1 Score: 0.9630423323338146
Average Precision: 0.9778183259141261
Average Recall: 0.9496978183962265

Q-LORA

In [17]:
pip install bitsandbytes

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting bitsandbytes
  Downloading bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: torch in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from bitsandbytes) (2.4.0)
Requirement already satisfied: numpy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.1.4)
Requirement already satisfied: fsspec in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->bitsandbytes) (12.6.20)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch->bitsandbytes) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch->bitsandbytes) (1.3.0)
Downloading bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl (122.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.4/122.4 MB 64.3 MB/s eta 0:00:0000:0100:01
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.44.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip install bitsandbytes --upgrade

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: bitsandbytes in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (0.44.1)
Requirement already satisfied: torch in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from bitsandbytes) (2.4.0)
Requirement already satisfied: numpy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.1.4)
Requirement already satisfied: fsspec in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->bitsandbytes) (12.6.20)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch->bitsandbytes) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch->bitsandbytes) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [19]:
pip install -U transformers peft datasets bitsandbytes

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: transformers in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (4.46.0)
Requirement already satisfied: peft in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: datasets in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (3.0.2)
Requirement already satisfied: bitsandbytes in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (0.44.1)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (3.15.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (0.24.5)
Requirement already satisfied: numpy>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (2024.7.24)
Requirement already satisfied: requests in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (0.4.4)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (0.20.1)
Requirement already satisfied: tqdm>=4.27 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (4.66.5)
Requirement already satisfied: psutil in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (6.0.0)
Requirement already satisfied: torch>=1.13.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (2.4.0)
Requirement already satisfied: accelerate>=0.21.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (1.0.1)
Requirement already satisfied: pyarrow>=15.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (2.2.2)
Requirement already satisfied: xxhash in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.6.1)
Requirement already satisfied: aiohttp in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from datasets) (3.10.10)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (1.16.0)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (2024.7.4)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13.0->peft) (12.6.20)
Requirement already satisfied: python-dateutil>=2.8.2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: six>=1.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: propcache>=0.2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch>=1.13.0->peft) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch>=1.13.0->peft) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [23]:
pip install --upgrade peft transformers

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: peft in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (0.13.2)
Requirement already satisfied: transformers in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (4.46.0)
Requirement already satisfied: numpy>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (24.1)
Requirement already satisfied: psutil in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (6.0.0)
Requirement already satisfied: pyyaml in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (6.0.2)
Requirement already satisfied: torch>=1.13.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (2.4.0)
Requirement already satisfied: tqdm in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (4.66.5)
Requirement already satisfied: accelerate>=0.21.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (1.0.1)
Requirement already satisfied: safetensors in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (0.4.4)
Requirement already satisfied: huggingface-hub>=0.17.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from peft) (0.24.5)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (3.15.4)
Requirement already satisfied: regex!=2019.12.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (2024.7.24)
Requirement already satisfied: requests in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from transformers) (0.20.1)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.17.0->peft) (2024.6.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.17.0->peft) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.13.0->peft) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13.0->peft) (12.6.20)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->transformers) (2024.7.4)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch>=1.13.0->peft) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch>=1.13.0->peft) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [17]:
pip show peft

Name: peft
Version: 0.13.2
Summary: Parameter-Efficient Fine-Tuning (PEFT)
Home-page: https://github.com/huggingface/peft
Author: The HuggingFace team
Author-email: benjamin@huggingface.co
License: Apache
Location: /root/miniconda3/envs/py3.10/lib/python3.10/site-packages
Requires: accelerate, huggingface-hub, numpy, packaging, psutil, pyyaml, safetensors, torch, tqdm, transformers
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [40]:
print(model)

GemmaForCausalLM(
  (model): GemmaModel(
    (embed_tokens): Embedding(256000, 2048, padding_idx=0)
    (layers): ModuleList(
      (0-17): 18 x GemmaDecoderLayer(
        (self_attn): GemmaSdpaAttention(
          (q_proj): lora.Linear(
            (base_layer): Linear(in_features=2048, out_features=2048, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.4, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=2048, out_features=2, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=2, out_features=2048, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (k_proj): Linear(in_features=2048, out_features=256, bias=False)
          (v_proj): lora.Linear(
            (base_layer): Linear(in_features=2048, out_features=256, bias=False)
            (lora_dropout): ModuleDict(
              (default): Dropout(p=0.4, inplace=False)
            )
            (lora_A): ModuleDict(
              (default): Linear(in_features=2048, out_features=2, bias=False)
            )
            (lora_B): ModuleDict(
              (default): Linear(in_features=2, out_features=256, bias=False)
            )
            (lora_embedding_A): ParameterDict()
            (lora_embedding_B): ParameterDict()
            (lora_magnitude_vector): ModuleDict()
          )
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (rotary_emb): GemmaRotaryEmbedding()
        )
        (mlp): GemmaMLP(
          (gate_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (up_proj): Linear(in_features=2048, out_features=16384, bias=False)
          (down_proj): Linear(in_features=16384, out_features=2048, bias=False)
          (act_fn): PytorchGELUTanh()
        )
        (input_layernorm): GemmaRMSNorm((2048,), eps=1e-06)
        (post_attention_layernorm): GemmaRMSNorm((2048,), eps=1e-06)
      )
    )
    (norm): GemmaRMSNorm((2048,), eps=1e-06)
  )
  (lm_head): Linear(in_features=2048, out_features=256000, bias=False)
)

In [44]:
pip install tensorboard

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting tensorboard
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting absl-py>=0.4 (from tensorboard)
  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
Collecting grpcio>=1.48.2 (from tensorboard)
  Downloading grpcio-1.67.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting markdown>=2.6.8 (from tensorboard)
  Downloading Markdown-3.7-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: numpy>=1.12.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from tensorboard) (1.26.4)
Requirement already satisfied: packaging in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from tensorboard) (24.1)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from tensorboard) (5.28.3)
Requirement already satisfied: setuptools>=41.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from tensorboard) (72.1.0)
Requirement already satisfied: six>1.9 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from tensorboard) (1.16.0)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard)
  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
Collecting werkzeug>=1.0.1 (from tensorboard)
  Downloading werkzeug-3.0.4-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=2.1.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard) (2.1.5)
Downloading tensorboard-2.18.0-py3-none-any.whl (5.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 11.2 MB/s eta 0:00:00a 0:00:01
Downloading absl_py-2.1.0-py3-none-any.whl (133 kB)
Downloading grpcio-1.67.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.9/5.9 MB 23.9 MB/s eta 0:00:00:00:01
Downloading Markdown-3.7-py3-none-any.whl (106 kB)
Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 75.3 MB/s eta 0:00:00
Downloading werkzeug-3.0.4-py3-none-any.whl (227 kB)
Installing collected packages: werkzeug, tensorboard-data-server, markdown, grpcio, absl-py, tensorboard
Successfully installed absl-py-2.1.0 grpcio-1.67.0 markdown-3.7 tensorboard-2.18.0 tensorboard-data-server-0.7.2 werkzeug-3.0.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [28]:
pip install accelerate

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Requirement already satisfied: accelerate in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (24.1)
Requirement already satisfied: psutil in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (6.0.0)
Requirement already satisfied: pyyaml in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=1.10.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (2.4.0)
Requirement already satisfied: huggingface-hub>=0.21.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (0.24.5)
Requirement already satisfied: safetensors>=0.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from accelerate) (0.4.4)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (3.15.4)
Requirement already satisfied: fsspec>=2023.5.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (2024.6.1)
Requirement already satisfied: requests in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (4.66.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from huggingface-hub>=0.21.0->accelerate) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.1.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch>=1.10.0->accelerate) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.10.0->accelerate) (12.6.20)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch>=1.10.0->accelerate) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2024.7.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch>=1.10.0->accelerate) (1.3.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [21]:
pip install -U bitsandbytes

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Collecting bitsandbytes
  Using cached bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: torch in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from bitsandbytes) (2.4.0)
Requirement already satisfied: numpy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from bitsandbytes) (1.26.4)
Requirement already satisfied: filelock in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (4.12.2)
Requirement already satisfied: sympy in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (1.13.2)
Requirement already satisfied: networkx in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.3)
Requirement already satisfied: jinja2 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.1.4)
Requirement already satisfied: fsspec in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (2024.6.1)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (12.1.105)
Requirement already satisfied: triton==3.0.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from torch->bitsandbytes) (3.0.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch->bitsandbytes) (12.6.20)
Requirement already satisfied: MarkupSafe>=2.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from jinja2->torch->bitsandbytes) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /root/miniconda3/envs/py3.10/lib/python3.10/site-packages (from sympy->torch->bitsandbytes) (1.3.0)
Using cached bitsandbytes-0.44.1-py3-none-manylinux_2_24_x86_64.whl (122.4 MB)
Installing collected packages: bitsandbytes
Successfully installed bitsandbytes-0.44.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Note: you may need to restart the kernel to use updated packages.

In [36]:
from peft import LoraConfig, get_peft_model
from transformers import Trainer, TrainingArguments, AutoModelForCausalLM, AutoTokenizer
from datasets import Dataset
from transformers import BitsAndBytesConfig
import torch

# Define the quantization configuration
quantization_config = BitsAndBytesConfig(
    load_in_8bit=True,  # Set to True for 8-bit quantization
    bnb_4bit=False,     # Set to True for 4-bit quantization if desired
)

# Load the model with quantization
model = AutoModelForCausalLM.from_pretrained(model_name, quantization_config=quantization_config)

# LoRA Configuration
lora_config = LoraConfig(
    r=2,                # Low-rank adaptation rank
    lora_alpha=8,      # Scaling factor for LoRA
    lora_dropout=0.4,   # Dropout probability for LoRA layers
    target_modules=["q_proj", "v_proj"],
)

# Apply LoRA to the quantized model
model_with_lora = get_peft_model(model, lora_config)


# Convert lists to Hugging Face Datasets
#train_dataset = Dataset.from_dict({k: [dic[k] for dic in train_dataset] for k in train_dataset[0]})
#val_dataset = Dataset.from_dict({k: [dic[k] for dic in val_dataset] for k in val_dataset[0]})

# Define Training Arguments
training_args = TrainingArguments(
    output_dir="./gemma_lora_quantized_results",
    per_device_train_batch_size=1,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    evaluation_strategy="steps",
    #save_strategy="steps",
    logging_dir="./logs",
    logging_steps=25,
    #save_steps=500,
    #eval_steps=500,
    learning_rate=1e-4,
    weight_decay=0.01,
    load_best_model_at_end=True,
    fp16 = True,
    bf16 = False,
    gradient_accumulation_steps = 8,
)

# Initialize the Trainer
trainer = Trainer(
    model=model_with_lora,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    tokenizer=tokenizer,
)

# Train the model with logging
try:
    trainer.train()
except Exception as e:
    print("Training failed with error:")
    print(e)

# Save the quantized model with LoRA
model_with_lora.save_pretrained("./fine_tuned_gemma_lora_quantized")

Unused kwargs: ['bnb_4bit']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
`low_cpu_mem_usage` was None, now set to True since model is quantized.

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

In [ ]:
def tokenize_function(examples):
    return tokenizer(examples["question"], examples["context"], truncation=True, padding="max_length", max_length=512)

train_dataset = train_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context']}), axis=1).tolist() # Apply tokenize_function to each row and convert to a list
val_dataset = val_malayalam.apply(lambda row: tokenize_function({'question': row['question'], 'context': row['context']}), axis=1).tolist() # Apply tokenize_function to each row and convert to a list

# Convert lists to Hugging Face Datasets
train_dataset = Dataset.from_dict({k: [dic[k] for dic in train_dataset] for k in train_dataset[0]})
val_dataset = Dataset.from_dict({k: [dic[k] for dic in val_dataset] for k in val_dataset[0]})

In [38]:
from tqdm import tqdm
import numpy as np
import torch
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score

import torch

# Define the device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# Initialize metrics
total_accuracy = 0
total_f1 = 0
total_precision = 0
total_recall = 0
total_samples = 0

# Custom evaluation loop with tqdm for progress
for batch in tqdm(val_dataset, desc="Evaluating"):
    # Move batch data to device
    input_ids = torch.tensor(batch['input_ids']).to(device)
    attention_mask = torch.tensor(batch['attention_mask']).to(device)
    labels = torch.tensor(batch['labels']).to(device)

    inputs = {
        'input_ids': input_ids.unsqueeze(0),
        'attention_mask': attention_mask.unsqueeze(0),
        'labels': labels.unsqueeze(0)
    }
    
    with torch.no_grad():
        outputs = model_with_lora(**inputs)

    # Get logits
    logits = outputs.logits
    predictions = torch.argmax(logits, dim=-1)  # Get class predictions

    # Print shapes for debugging
    print("Logits shape:", logits.shape)  # Should be [1, 512, num_classes]
    print("Labels shape:", labels.shape)    # Should be [512]
    print("Predictions shape:", predictions.shape)  # Should be [1, 512]

    # Flatten the predictions and labels
    predictions = predictions.view(-1).cpu().numpy()  # Shape: [512]
    labels = labels.view(-1).cpu().numpy()            # Shape: [512]

    # Check lengths
    if len(labels) == len(predictions):
        total_accuracy += accuracy_score(labels, predictions)
        total_f1 += f1_score(labels, predictions, average='weighted', zero_division=0)
        total_precision += precision_score(labels, predictions, average='weighted', zero_division=0)
        total_recall += recall_score(labels, predictions, average='weighted', zero_division=0)
        total_samples += 1
    else:
        print(f"Inconsistent sizes: labels {len(labels)} predictions {len(predictions)}")

# Calculate average metrics
if total_samples > 0:
    avg_accuracy = total_accuracy / total_samples
    avg_f1 = total_f1 / total_samples
    avg_precision = total_precision / total_samples
    avg_recall = total_recall / total_samples

    # Print results
    print("Average Accuracy:", avg_accuracy)
    print("Average F1 Score:", avg_f1)
    print("Average Precision:", avg_precision)
    print("Average Recall:", avg_recall)
else:
    print("No valid samples for metrics calculation.")

Using device: cuda

Evaluating:   1%|▏         | 2/159 [00:00<00:32,  4.78it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   3%|▎         | 4/159 [00:00<00:28,  5.48it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   4%|▍         | 6/159 [00:01<00:26,  5.72it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   5%|▌         | 8/159 [00:01<00:25,  5.84it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   6%|▋         | 10/159 [00:01<00:25,  5.90it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   8%|▊         | 12/159 [00:02<00:24,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:   9%|▉         | 14/159 [00:02<00:24,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  10%|█         | 16/159 [00:02<00:24,  5.88it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  11%|█▏        | 18/159 [00:03<00:23,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  13%|█▎        | 20/159 [00:03<00:23,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  14%|█▍        | 22/159 [00:03<00:23,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  15%|█▌        | 24/159 [00:04<00:22,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  16%|█▋        | 26/159 [00:04<00:22,  5.90it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  18%|█▊        | 28/159 [00:04<00:22,  5.90it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  19%|█▉        | 30/159 [00:05<00:21,  5.88it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  20%|██        | 32/159 [00:05<00:21,  5.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  21%|██▏       | 34/159 [00:05<00:21,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  23%|██▎       | 36/159 [00:06<00:20,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  24%|██▍       | 38/159 [00:06<00:20,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  25%|██▌       | 40/159 [00:06<00:19,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  26%|██▋       | 42/159 [00:07<00:19,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  28%|██▊       | 44/159 [00:07<00:19,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  29%|██▉       | 46/159 [00:07<00:19,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  30%|███       | 48/159 [00:08<00:18,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  31%|███▏      | 50/159 [00:08<00:18,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  33%|███▎      | 52/159 [00:08<00:18,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  34%|███▍      | 54/159 [00:09<00:17,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  35%|███▌      | 56/159 [00:09<00:17,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  36%|███▋      | 58/159 [00:09<00:16,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  38%|███▊      | 60/159 [00:10<00:16,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  39%|███▉      | 62/159 [00:10<00:16,  5.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  40%|████      | 64/159 [00:10<00:16,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  42%|████▏     | 66/159 [00:11<00:15,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  43%|████▎     | 68/159 [00:11<00:15,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  44%|████▍     | 70/159 [00:11<00:15,  5.88it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  45%|████▌     | 72/159 [00:12<00:14,  5.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  47%|████▋     | 74/159 [00:12<00:14,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  48%|████▊     | 76/159 [00:12<00:13,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  49%|████▉     | 78/159 [00:13<00:13,  5.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  50%|█████     | 80/159 [00:13<00:13,  5.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  52%|█████▏    | 82/159 [00:13<00:12,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  53%|█████▎    | 84/159 [00:14<00:12,  5.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  54%|█████▍    | 86/159 [00:14<00:12,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  55%|█████▌    | 88/159 [00:14<00:11,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  57%|█████▋    | 90/159 [00:15<00:11,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  58%|█████▊    | 92/159 [00:15<00:11,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  59%|█████▉    | 94/159 [00:15<00:10,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  60%|██████    | 96/159 [00:16<00:10,  5.96it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  62%|██████▏   | 98/159 [00:16<00:10,  5.89it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  63%|██████▎   | 100/159 [00:16<00:09,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  64%|██████▍   | 102/159 [00:17<00:09,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  65%|██████▌   | 104/159 [00:17<00:09,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  67%|██████▋   | 106/159 [00:17<00:08,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  68%|██████▊   | 108/159 [00:18<00:08,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  69%|██████▉   | 110/159 [00:18<00:08,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  70%|███████   | 112/159 [00:18<00:07,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  72%|███████▏  | 114/159 [00:19<00:07,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  73%|███████▎  | 116/159 [00:19<00:07,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  74%|███████▍  | 118/159 [00:19<00:06,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  75%|███████▌  | 120/159 [00:20<00:06,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  77%|███████▋  | 122/159 [00:20<00:06,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  78%|███████▊  | 124/159 [00:21<00:05,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  79%|███████▉  | 126/159 [00:21<00:05,  5.93it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  81%|████████  | 128/159 [00:21<00:05,  5.92it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  82%|████████▏ | 130/159 [00:22<00:04,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  83%|████████▎ | 132/159 [00:22<00:04,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  84%|████████▍ | 134/159 [00:22<00:04,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  86%|████████▌ | 136/159 [00:23<00:03,  5.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  87%|████████▋ | 138/159 [00:23<00:03,  5.96it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  88%|████████▊ | 140/159 [00:23<00:03,  5.96it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  89%|████████▉ | 142/159 [00:24<00:02,  5.94it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  91%|█████████ | 144/159 [00:24<00:02,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  92%|█████████▏| 146/159 [00:24<00:02,  5.95it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  93%|█████████▎| 148/159 [00:25<00:01,  5.96it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  94%|█████████▍| 150/159 [00:25<00:01,  5.97it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  96%|█████████▌| 152/159 [00:25<00:01,  5.96it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  97%|█████████▋| 154/159 [00:26<00:00,  5.96it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  98%|█████████▊| 156/159 [00:26<00:00,  5.88it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating:  99%|█████████▉| 158/159 [00:26<00:00,  5.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])

Evaluating: 100%|██████████| 159/159 [00:26<00:00,  5.91it/s]

Logits shape: torch.Size([1, 512, 256000])
Labels shape: torch.Size([512])
Predictions shape: torch.Size([1, 512])
Average Accuracy: 0.8949488993710691
Average F1 Score: 0.9339344043102685
Average Precision: 0.9778028143224051
Average Recall: 0.8949488993710691